#!/bin/bash
#
# Simple script for doing job submission dialogs with Zenity
#
# Written by: Brian Smith <brs@usf.edu>
#

SGERUN_HOME=/opt/admin/sgerun-0.1
[ -f "$SGERUN_HOME/sgerun.conf" ] && . $SGERUN_HOME/sgerun.conf
[ -f "$SGERUN_HOME/functions.conf" ] && . $SGERUN_HOME/functions.conf

app=$1
module add apps/$app

[ -f "$SGERUN_HOME/zenity_functions.conf" ] && . $SGERUN_HOME/zenity_functions.conf

if zprompt $app; then
	if [[ "$@" =~ "directory" ]]; then
		dir=$(zdir)
		[ -z "$dir" ] && exit
	fi
	if [[ "$@" =~ "cpus" ]]; then
		procs=$(zprocs)
		[ -z "$procs" ] && exit
		args="$args -n $procs"
	fi
	if [[ "$@" =~ "memory" ]]; then
		mem=$(zmem)
		[ -z "$mem" ] && exit
		args="$args -m $mem"
	fi
	if [[ "$@" =~ "runtime" ]]; then
		rt=$(zrt)
		[ -z "$rt" ] && exit
		args="$args -t $rt"
	fi
	if [[ "$@" =~ "env" ]]; then
		environ=$(echo $@ | egrep -o "env=[^ ]*")
		args="$args -e ${environ//env=/}"
	fi

	[ -n "$dir" ] && cd $dir
	echo run -i $args $app
	output=$(run -v -i $args $app 2>&1)
	if [ $? -eq 0 ]; then
		! [[ "$@" =~ "erroronly" ]] && echo "$output" | zenity --width=640 --height=480 --title="Process Output" --text-info
	else
		echo "$output" | zenity --width=640 --height=480 --title="Process Output" --text-info
	fi
else
	exit
fi
